///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Spar.Test_cases.Registration
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The iOS_Registration_SerialNumber_Valid recording.
    /// </summary>
    [TestModule("87317fdc-4279-4ea7-a4b0-420dbf3c4918", ModuleType.Recording, 1)]
    public partial class iOS_Registration_SerialNumber_Valid : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Spar.SparRepository repository.
        /// </summary>
        public static Spar.SparRepository repo = Spar.SparRepository.Instance;

        static iOS_Registration_SerialNumber_Valid instance = new iOS_Registration_SerialNumber_Valid();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public iOS_Registration_SerialNumber_Valid()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static iOS_Registration_SerialNumber_Valid Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run mobile app 'com.inovaint.spar' on device 'iPhone7'.", new RecordItemIndex(0));
            Host.Local.RunMobileApp("iPhone7", "com.inovaint.spar", true);
            Delay.Milliseconds(3500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComInovaintSpar.Registration.LandingScreen.VpišiteSerijskoŠtevilkoKartice' at Center", repo.ComInovaintSpar.Registration.LandingScreen.VpišiteSerijskoŠtevilkoKarticeInfo, new RecordItemIndex(1));
            repo.ComInovaintSpar.Registration.LandingScreen.VpišiteSerijskoŠtevilkoKartice.Touch();
            Delay.Milliseconds(500);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
