///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Spar.Test_cases.Registration
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The iOS_NoCard_Registration_Success recording.
    /// </summary>
    [TestModule("81b4ca1d-2c8b-4ed3-8bc7-111c9c666dd4", ModuleType.Recording, 1)]
    public partial class IOS_NoCard_Registration_Success : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Spar.SparRepository repository.
        /// </summary>
        public static Spar.SparRepository repo = Spar.SparRepository.Instance;

        static IOS_NoCard_Registration_Success instance = new IOS_NoCard_Registration_Success();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public IOS_NoCard_Registration_Success()
        {
            iOSFirstName = "";
            iOSLastName = "";
            iOSBirthDate = "";
            iOSCountry = "Slovenija";
            iOSStreet = "Cirknica";
            iOSHouseNumber = "26";
            iOSPostNumber = "2212";
            iOSCity = "Šentilj";
            iOSMobilePhone = "040305750";
            iOSEmail = "domen.fras@gmail.com";
            iOSPassword = "Adgjadgj1";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static IOS_NoCard_Registration_Success Instance
        {
            get { return instance; }
        }

#region Variables

        string _iOSFirstName;

        /// <summary>
        /// Gets or sets the value of variable iOSFirstName.
        /// </summary>
        [TestVariable("fa269eff-c254-4536-adf7-f3fef5f535a3")]
        public string iOSFirstName
        {
            get { return _iOSFirstName; }
            set { _iOSFirstName = value; }
        }

        string _iOSLastName;

        /// <summary>
        /// Gets or sets the value of variable iOSLastName.
        /// </summary>
        [TestVariable("a75a0a14-8da3-4874-9156-9f738401d45e")]
        public string iOSLastName
        {
            get { return _iOSLastName; }
            set { _iOSLastName = value; }
        }

        string _iOSBirthDate;

        /// <summary>
        /// Gets or sets the value of variable iOSBirthDate.
        /// </summary>
        [TestVariable("267179b9-ddfe-48f3-9fc5-468ab7c98b65")]
        public string iOSBirthDate
        {
            get { return _iOSBirthDate; }
            set { _iOSBirthDate = value; }
        }

        string _iOSCountry;

        /// <summary>
        /// Gets or sets the value of variable iOSCountry.
        /// </summary>
        [TestVariable("4d166403-ff31-4844-a6de-8b899c411e8b")]
        public string iOSCountry
        {
            get { return _iOSCountry; }
            set { _iOSCountry = value; }
        }

        string _iOSStreet;

        /// <summary>
        /// Gets or sets the value of variable iOSStreet.
        /// </summary>
        [TestVariable("d88dd6f3-5fb1-4ee4-8b86-3fa2271ab003")]
        public string iOSStreet
        {
            get { return _iOSStreet; }
            set { _iOSStreet = value; }
        }

        string _iOSHouseNumber;

        /// <summary>
        /// Gets or sets the value of variable iOSHouseNumber.
        /// </summary>
        [TestVariable("cc5fae92-18b9-482b-82fd-aeef8d0397a5")]
        public string iOSHouseNumber
        {
            get { return _iOSHouseNumber; }
            set { _iOSHouseNumber = value; }
        }

        string _iOSPostNumber;

        /// <summary>
        /// Gets or sets the value of variable iOSPostNumber.
        /// </summary>
        [TestVariable("3962626b-7c3c-42d2-a449-7e1ce4814288")]
        public string iOSPostNumber
        {
            get { return _iOSPostNumber; }
            set { _iOSPostNumber = value; }
        }

        string _iOSCity;

        /// <summary>
        /// Gets or sets the value of variable iOSCity.
        /// </summary>
        [TestVariable("a010052c-a383-4868-88b6-81b31f24e715")]
        public string iOSCity
        {
            get { return _iOSCity; }
            set { _iOSCity = value; }
        }

        string _iOSMobilePhone;

        /// <summary>
        /// Gets or sets the value of variable iOSMobilePhone.
        /// </summary>
        [TestVariable("843c7242-7e0e-4fd2-b852-702d68c1372d")]
        public string iOSMobilePhone
        {
            get { return _iOSMobilePhone; }
            set { _iOSMobilePhone = value; }
        }

        string _iOSEmail;

        /// <summary>
        /// Gets or sets the value of variable iOSEmail.
        /// </summary>
        [TestVariable("205b987d-9cb2-4f45-9901-539f561feda9")]
        public string iOSEmail
        {
            get { return _iOSEmail; }
            set { _iOSEmail = value; }
        }

        string _iOSPassword;

        /// <summary>
        /// Gets or sets the value of variable iOSPassword.
        /// </summary>
        [TestVariable("8ca26a42-5202-40d5-acc0-e9170ac38bef")]
        public string iOSPassword
        {
            get { return _iOSPassword; }
            set { _iOSPassword = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.2")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Caption='Pričnite tako, da skenirate svojo SPAR plus kartico!') on item 'ComInovaintSpar.Registration.LandingScreen.PričniteTakoDaSkenirateSvojoSPARP'.", repo.ComInovaintSpar.Registration.LandingScreen.PričniteTakoDaSkenirateSvojoSPARPInfo, new RecordItemIndex(0));
            Validate.Attribute(repo.ComInovaintSpar.Registration.LandingScreen.PričniteTakoDaSkenirateSvojoSPARPInfo, "Caption", "Pričnite tako, da skenirate svojo SPAR plus kartico!");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComInovaintSpar.Registration.LandingScreen.NimamSPARPlusKartice' at Center", repo.ComInovaintSpar.Registration.LandingScreen.NimamSPARPlusKarticeInfo, new RecordItemIndex(1));
            repo.ComInovaintSpar.Registration.LandingScreen.NimamSPARPlusKartice.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Caption='Postani član SPAR plus') on item 'ComInovaintSpar.Registration.Registration_NoCard_Join.PostaniČlanSPARPlus'.", repo.ComInovaintSpar.Registration.Registration_NoCard_Join.PostaniČlanSPARPlusInfo, new RecordItemIndex(2));
            Validate.Attribute(repo.ComInovaintSpar.Registration.Registration_NoCard_Join.PostaniČlanSPARPlusInfo, "Caption", "Postani član SPAR plus");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Caption='Ekskluzivni kuponi in ugodnosti') on item 'ComInovaintSpar.Registration.Registration_NoCard_Join.EkskluzivniKuponiInUgodnosti'.", repo.ComInovaintSpar.Registration.Registration_NoCard_Join.EkskluzivniKuponiInUgodnostiInfo, new RecordItemIndex(3));
            Validate.Attribute(repo.ComInovaintSpar.Registration.Registration_NoCard_Join.EkskluzivniKuponiInUgodnostiInfo, "Caption", "Ekskluzivni kuponi in ugodnosti");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Caption='Zbiranje dobropisa na kartici') on item 'ComInovaintSpar.Registration.Registration_NoCard_Join.ZbiranjeDobropisaNaKartici'.", repo.ComInovaintSpar.Registration.Registration_NoCard_Join.ZbiranjeDobropisaNaKarticiInfo, new RecordItemIndex(4));
            Validate.Attribute(repo.ComInovaintSpar.Registration.Registration_NoCard_Join.ZbiranjeDobropisaNaKarticiInfo, "Caption", "Zbiranje dobropisa na kartici");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Caption='Dostop do SPAR plus kartice kar na telefonu') on item 'ComInovaintSpar.Registration.Registration_NoCard_Join.DostopDoSPARPlusKarticeKarNaTelef'.", repo.ComInovaintSpar.Registration.Registration_NoCard_Join.DostopDoSPARPlusKarticeKarNaTelefInfo, new RecordItemIndex(5));
            Validate.Attribute(repo.ComInovaintSpar.Registration.Registration_NoCard_Join.DostopDoSPARPlusKarticeKarNaTelefInfo, "Caption", "Dostop do SPAR plus kartice kar na telefonu");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComInovaintSpar.Registration.Registration_NoCard_Join.PridružiteSe' at Center", repo.ComInovaintSpar.Registration.Registration_NoCard_Join.PridružiteSeInfo, new RecordItemIndex(6));
            repo.ComInovaintSpar.Registration.Registration_NoCard_Join.PridružiteSe.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$iOSFirstName' on item 'ComInovaintSpar.Registration.Registration_NoCard_PersonalData.Ime'.", repo.ComInovaintSpar.Registration.Registration_NoCard_PersonalData.ImeInfo, new RecordItemIndex(7));
            repo.ComInovaintSpar.Registration.Registration_NoCard_PersonalData.Ime.Element.SetAttributeValue("Text", iOSFirstName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$iOSLastName' on item 'ComInovaintSpar.Registration.Registration_NoCard_PersonalData.Priimek'.", repo.ComInovaintSpar.Registration.Registration_NoCard_PersonalData.PriimekInfo, new RecordItemIndex(8));
            repo.ComInovaintSpar.Registration.Registration_NoCard_PersonalData.Priimek.Element.SetAttributeValue("Text", iOSLastName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$iOSBirthDate' on item 'ComInovaintSpar.Registration.Registration_NoCard_PersonalData.DatumRojstva'.", repo.ComInovaintSpar.Registration.Registration_NoCard_PersonalData.DatumRojstvaInfo, new RecordItemIndex(9));
            repo.ComInovaintSpar.Registration.Registration_NoCard_PersonalData.DatumRojstva.Element.SetAttributeValue("Text", iOSBirthDate);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComInovaintSpar.Registration.Registration_NoCard_PersonalData.Spol' at Center", repo.ComInovaintSpar.Registration.Registration_NoCard_PersonalData.SpolInfo, new RecordItemIndex(10));
            repo.ComInovaintSpar.Registration.Registration_NoCard_PersonalData.Spol.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComInovaintSpar.Registration.Registration_NoCard_PersonalData.Moški' at Center", repo.ComInovaintSpar.Registration.Registration_NoCard_PersonalData.MoškiInfo, new RecordItemIndex(11));
            repo.ComInovaintSpar.Registration.Registration_NoCard_PersonalData.Moški.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComInovaintSpar.Registration.CommonElements.Naprej' at Center", repo.ComInovaintSpar.Registration.CommonElements.NaprejInfo, new RecordItemIndex(12));
            repo.ComInovaintSpar.Registration.CommonElements.Naprej.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Caption='Vpišite podatke o prebivališču') on item 'ComInovaintSpar.Registration.Registration_NoCard_Address.VpišitePodatkeOPrebivališču'.", repo.ComInovaintSpar.Registration.Registration_NoCard_Address.VpišitePodatkeOPrebivališčuInfo, new RecordItemIndex(13));
            Validate.Attribute(repo.ComInovaintSpar.Registration.Registration_NoCard_Address.VpišitePodatkeOPrebivališčuInfo, "Caption", "Vpišite podatke o prebivališču");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$iOSCountry' on item 'ComInovaintSpar.Registration.Registration_NoCard_Address.Država'.", repo.ComInovaintSpar.Registration.Registration_NoCard_Address.DržavaInfo, new RecordItemIndex(14));
            repo.ComInovaintSpar.Registration.Registration_NoCard_Address.Država.Element.SetAttributeValue("Text", iOSCountry);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$iOSStreet' on item 'ComInovaintSpar.Registration.Registration_NoCard_Address.Ulica'.", repo.ComInovaintSpar.Registration.Registration_NoCard_Address.UlicaInfo, new RecordItemIndex(15));
            repo.ComInovaintSpar.Registration.Registration_NoCard_Address.Ulica.Element.SetAttributeValue("Text", iOSStreet);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$iOSHouseNumber' on item 'ComInovaintSpar.Registration.Registration_NoCard_Address.HišnaŠtevilka'.", repo.ComInovaintSpar.Registration.Registration_NoCard_Address.HišnaŠtevilkaInfo, new RecordItemIndex(16));
            repo.ComInovaintSpar.Registration.Registration_NoCard_Address.HišnaŠtevilka.Element.SetAttributeValue("Text", iOSHouseNumber);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$iOSPostNumber' on item 'ComInovaintSpar.Registration.Registration_NoCard_Address.PoštnaŠtevilka'.", repo.ComInovaintSpar.Registration.Registration_NoCard_Address.PoštnaŠtevilkaInfo, new RecordItemIndex(17));
            repo.ComInovaintSpar.Registration.Registration_NoCard_Address.PoštnaŠtevilka.Element.SetAttributeValue("Text", iOSPostNumber);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$iOSCity' on item 'ComInovaintSpar.Registration.Registration_NoCard_Address.Kraj'.", repo.ComInovaintSpar.Registration.Registration_NoCard_Address.KrajInfo, new RecordItemIndex(18));
            repo.ComInovaintSpar.Registration.Registration_NoCard_Address.Kraj.Element.SetAttributeValue("Text", iOSCity);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key '{ENTER}' press on 'ComInovaintSpar'.", repo.ComInovaintSpar.SelfInfo, new RecordItemIndex(19));
            repo.ComInovaintSpar.Self.PressKeys("{ENTER}");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComInovaintSpar.Registration.CommonElements.Naprej' at Center", repo.ComInovaintSpar.Registration.CommonElements.NaprejInfo, new RecordItemIndex(20));
            repo.ComInovaintSpar.Registration.CommonElements.Naprej.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Caption='Vpišite podatke za prijavo') on item 'ComInovaintSpar.Registration.Registration_NoCard_Data.VpišitePodatkeZaPrijavo'.", repo.ComInovaintSpar.Registration.Registration_NoCard_Data.VpišitePodatkeZaPrijavoInfo, new RecordItemIndex(21));
            Validate.Attribute(repo.ComInovaintSpar.Registration.Registration_NoCard_Data.VpišitePodatkeZaPrijavoInfo, "Caption", "Vpišite podatke za prijavo");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$iOSMobilePhone' on item 'ComInovaintSpar.Registration.Registration_NoCard_Data.ŠtevilkaMobilnegaTelefona'.", repo.ComInovaintSpar.Registration.Registration_NoCard_Data.ŠtevilkaMobilnegaTelefonaInfo, new RecordItemIndex(22));
            repo.ComInovaintSpar.Registration.Registration_NoCard_Data.ŠtevilkaMobilnegaTelefona.Element.SetAttributeValue("Text", iOSMobilePhone);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$iOSEmail' on item 'ComInovaintSpar.Registration.Registration_NoCard_Data.EMailNaslov'.", repo.ComInovaintSpar.Registration.Registration_NoCard_Data.EMailNaslovInfo, new RecordItemIndex(23));
            repo.ComInovaintSpar.Registration.Registration_NoCard_Data.EMailNaslov.Element.SetAttributeValue("Text", iOSEmail);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$iOSPassword' on item 'ComInovaintSpar.Registration.Registration_NoCard_Data.Geslo'.", repo.ComInovaintSpar.Registration.Registration_NoCard_Data.GesloInfo, new RecordItemIndex(24));
            repo.ComInovaintSpar.Registration.Registration_NoCard_Data.Geslo.Element.SetAttributeValue("Text", iOSPassword);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set Value", "Setting attribute Text to '$iOSPassword' on item 'ComInovaintSpar.Registration.Registration_NoCard_Data.PonoviGeslo'.", repo.ComInovaintSpar.Registration.Registration_NoCard_Data.PonoviGesloInfo, new RecordItemIndex(25));
            repo.ComInovaintSpar.Registration.Registration_NoCard_Data.PonoviGeslo.Element.SetAttributeValue("Text", iOSPassword);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key '{ENTER}' press on 'ComInovaintSpar'.", repo.ComInovaintSpar.SelfInfo, new RecordItemIndex(26));
            repo.ComInovaintSpar.Self.PressKeys("{ENTER}");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComInovaintSpar.Registration.CommonElements.Naprej' at Center", repo.ComInovaintSpar.Registration.CommonElements.NaprejInfo, new RecordItemIndex(27));
            repo.ComInovaintSpar.Registration.CommonElements.Naprej.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Caption='Dodatne informacije') on item 'ComInovaintSpar.Registration.Registration_NoCard_AdditionalData.DodatneInformacije'.", repo.ComInovaintSpar.Registration.Registration_NoCard_AdditionalData.DodatneInformacijeInfo, new RecordItemIndex(28));
            Validate.Attribute(repo.ComInovaintSpar.Registration.Registration_NoCard_AdditionalData.DodatneInformacijeInfo, "Caption", "Dodatne informacije");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComInovaintSpar.Registration.CommonElements.Naprej' at Center", repo.ComInovaintSpar.Registration.CommonElements.NaprejInfo, new RecordItemIndex(29));
            repo.ComInovaintSpar.Registration.CommonElements.Naprej.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Caption='Ne spreglejte kuponov in promocij') on item 'ComInovaintSpar.Registration.Registration_Permissions.Permissions_CommonElements.NeSpreglejteKuponovInPromocij'.", repo.ComInovaintSpar.Registration.Registration_Permissions.Permissions_CommonElements.NeSpreglejteKuponovInPromocijInfo, new RecordItemIndex(30));
            Validate.Attribute(repo.ComInovaintSpar.Registration.Registration_Permissions.Permissions_CommonElements.NeSpreglejteKuponovInPromocijInfo, "Caption", "Ne spreglejte kuponov in promocij");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComInovaintSpar.Registration.CommonElements.Preskoči' at Center", repo.ComInovaintSpar.Registration.CommonElements.PreskočiInfo, new RecordItemIndex(31));
            repo.ComInovaintSpar.Registration.CommonElements.Preskoči.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Caption='Kje je najbližji Spar?') on item 'ComInovaintSpar.Registration.Registration_Permissions.Permission_Location.KjeJeNajbližjiSpar'.", repo.ComInovaintSpar.Registration.Registration_Permissions.Permission_Location.KjeJeNajbližjiSparInfo, new RecordItemIndex(32));
            Validate.Attribute(repo.ComInovaintSpar.Registration.Registration_Permissions.Permission_Location.KjeJeNajbližjiSparInfo, "Caption", "Kje je najbližji Spar?");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComInovaintSpar.Registration.CommonElements.Preskoči' at Center", repo.ComInovaintSpar.Registration.CommonElements.PreskočiInfo, new RecordItemIndex(33));
            repo.ComInovaintSpar.Registration.CommonElements.Preskoči.Touch();
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComInovaintSpar.Registration.Registration_Permissions.SparCardAlwaysAccessible.Dokončaj' at Center", repo.ComInovaintSpar.Registration.Registration_Permissions.SparCardAlwaysAccessible.DokončajInfo, new RecordItemIndex(34));
            repo.ComInovaintSpar.Registration.Registration_Permissions.SparCardAlwaysAccessible.Dokončaj.Touch();
            Delay.Milliseconds(500);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
